name: Nightly Featured Snippet Pull

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  pull-snippets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run snippet pull script
        env:
          INTERNAL_PUBLIC_AUTOMATIONS_SECRET_KEY: ${{ secrets.INTERNAL_PUBLIC_AUTOMATIONS_SECRET_KEY }}
        run: bun run scripts/pull-featured-snippets.ts

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update featured snippets" && git push)
